sudo: required

services:
- docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

script:
    - export REPO_VAULTINIT=richardcase/vault-admission
    - export VERSION=`cat ./VERSION`
    - export BUILDDATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
    - echo $VERSION
    - echo $BUILDDATE
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker build -f  Dockerfile -t $REPO_VAULTINIT:$COMMIT --build-arg BUILD_DATE=$BUILDDATE --build-arg VCS_REF=$COMMIT --build-arg VERSION=$VERSION .
    - docker tag $REPO_VAULTINIT:$COMMIT $REPO_VAULTINIT:$TAG
    - docker tag $REPO_VAULTINIT:$COMMIT $REPO_VAULTINIT:travis-$TRAVIS_BUILD_NUMBER
    - docker tag $REPO_VAULTINIT:$COMMIT $REPO_VAULTINIT:$VERSION
    - docker push $REPO_VAULTINIT

env:
    global:
        - COMMIT=${TRAVIS_COMMIT::8}
