apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: vault-admission.k8s.io
webhooks:
  - name: vault-admission.k8s.io
    clientConfig:
        service:
          name: vault-admission
          namespace: default
          path: "/inject"
        caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRREpzT2RMSmROcmJqQU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05NVGd3TlRJMU1URXdOelF4V2hnUE1qSTVNakF6TURreE1UQTNOREZhTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU0wYVFQVU9ma0dra1FianNFTHovRUdPMnROMVJKdUY3ZFVGa3VwYVl6ZXliK0RTVXlIMWk3d28KVVFZc1NJZzIxdUJOLzNFRmJvL2tVOVEwcWR3d3BNaDZOZkh4cVYzcUErMzcrYTBBc2x6d0NuNmlNajQwUk9nWQpDb2VGV0VqY3licTB0OWhPci9yTHNJWnh4S011b0xkSTBRNkZMTVFHNlB5TWtFSkhZUGhIRXNsTlBPVjZTclAzCklNK0U1T2pKMXdmQVY1SDVBQStPd1RGVi9yNnRaSE5yOHhQWXN4anhmbWhiR3MyN0lOSzNwRklCbkl1SmJBaHoKQjUvb0o0V1N1Nm90MFJ1M0NISDUvd3F2WkZKNlhqTThocDRpOGFkTnEwbU4rOE42NFJnR1dYK2V1UkYxTFpPOApIU1ZWakVtS21JYzVaWTI1RUtvVGhzUzN4VFhpeEFjQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBClhwYngwNHRvNlJSdzNlTjdGS2htd2tjQUV6WlF3YUNCRHhYQ0hGaGxaWkJwWVBHSHpvUldud0ZBU1p3TDZWREoKd2RWczRYNy80RnM2cEZvejAwQUpCZGVZbWU3NThZK0gzZGQxU1d4cVRoWjVBTGlzMnpBbGVBck9MZk9KT3BCNQp0cUlqTy9xOWt0UjB5bjM0M1huZ3dmelc2ZEFoc3VwNzYzWlkvL3V1VlVtaS9udFUrRUhnYmZCTktnL1ZsdW9qCnpuaktLcXUyRVBKemFvWFU5K0dHN0E1ZWtramV2QzFxMWNtQ1Znc1RrTStnMG4vd2dubG1admRoNURMOFdOTUYKd3UrTTZrWURyR21sNXkwVFl2T1NKUStadXlNd0FHYXRpNFlKNllEUGVSaUROZHh2Ym9CNUJqUjdiK2V5NjNXWgp3a2pYT2sxSFpCU2ZicEQ2WWFSNVJBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    namespaceSelector:
        matchLabels:
            secrets-injection: enabled
