apiVersion: v1
kind: Service
metadata:
  labels:
    role: vault-admission-debug
  name: vault-admission-debug
spec:
  type: NodePort
  ports:
    - name: delve 
      port: 2345
      targetPort: 2345
      nodePort: 32345
  selector:
    app: vault-admission
